sudo: required
services:
  - docker

env:
#    global:
#      - PRODUCT=haproxy
    matrix:
      - OS=centos DIST=6 PACK=rpm
      - OS=centos DIST=7 PACK=rpm
#      - OS=fedora DIST=22 PACK=rpm
#      - OS=fedora DIST=23 PACK=rpm
#      - OS=fedora DIST=24 PACK=rpm
#      - OS=fedora DIST=rawhide PACK=rpm
#      - OS=ubuntu DIST=trusty PACK=deb
#      - OS=ubuntu DIST=precise PACK=deb
#      - OS=ubuntu DIST=wily PACK=deb
#      - OS=ubuntu DIST=xenial PACK=deb
#      - OS=debian DIST=jessie PACK=deb
#      - OS=debian DIST=wheezy PACK=deb
#      - OS=debian DIST=stretch PACK=deb
#      - OS=debian DIST=sid PACK=deb
#      - PACK=none

script:
#  - git clone https://github.com/resnostyle/build.git
#  - git clone https://github.com/tarantool/build.git
#  - git clone https://github.com/tarantool/build.git
  - ./package.sh

#notifications:
#  email: true
#  irc: false

before_install:
  - gem install package_cloud

script:
    - package_cloud push resnostyle/tinc/OS/DIST 
